name: Publish Documentation branch

on:
  push:
    paths:
      - '.github/workflows/docs.yml'
      - 'docs/*'

jobs:
  docs-build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Build
      run: npm i && cd docs && npm i && npm run export --basepath fulmo

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs/__sapper__/export